Feature/auth
sze-projektmunka-slack-bot/slack-bot pull request #3
Opened 2021-11-09 18:09 UTC by tamastomordi

Mindenképp nézd meg légyszi, hogy minden jól működik -e és elfogadható -e neked a kód.

2021-11-10 03:09 UTC, tamasori requested changes
Nem látok benne semmi olyan nagy gondot, viszont az érdekelne, hogy mi történt a public mappával? Hogy teli lett jsx fájlokkal, meg rendezetlen fájlokkal. A react cli-nek van beépített buildere, amivel ki lehet buildelni egy rendes verziót. Plusz ahogy nézem a public mappában lévő fájlok ismétlődnek az src-ből.

2021-11-10 03:09 UTC, tamasori commented on frontend/src/actions/index.js
> +        console.log(response);
Log-ot majd szedd ki

2021-11-10 03:09 UTC, tamasori commented on frontend/src/components/button/button.jsx
>      );
Miért lett div a button?

2021-11-10 03:09 UTC, tamasori commented on frontend/src/pages/Signup/Signup.jsx
> +            }
Erre szerintem inkább kérd meg a Petit, hogy csináljon magyar errorokat, vagy kódokat adjon meg, mert ha a Laravel frissül, és megváltozik az alap szöveg, akkor már nem fog menni ez így.

2021-11-10 06:27 UTC, tamastomordi commented on frontend/public/Signup.jsx
> +        props.signup('tamastomordi', 'thefurgeurge@gmail.com', 'ABC123456', 'ABC123456');
Töröltem ezt a pár jsx fájlt a publicból. Az a vicces, hogy nem tudom ezek miért kerültek oda.

2021-11-10 06:28 UTC, tamastomordi commented on frontend/public/index.js
> +};
De. Törölve. Nem tudom ez is miért került oda.

2021-11-10 06:30 UTC, tamastomordi commented on frontend/src/App.js
> +            </Routes>
`<Route path="*" exact element={<Navigate to={defRouteAfterLogIn} />} />`
Ez most is így működik, ha bármit elírnak, átirányít a default page-re.

2021-11-10 06:31 UTC, tamastomordi commented on frontend/src/pages/Signup/Signup.jsx
> +            }
@mushukcha

2021-11-10 06:35 UTC, tamastomordi commented on frontend/public/index.js
> +};
Végül is igaz. Kivettem.

2021-11-10 06:37 UTC, tamastomordi commented on frontend/src/components/button/button.jsx
>      );
Technikai okok miatt. Amik már nem állnak fenn. Szóval visszaraktam button-ra.

2021-11-12 17:11 UTC, tamasori approved these changes

2021-11-12 17:11 UTC, merged